# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ['.c9']

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

url: http://datasf.org
defaultbranch: gh-pages

paginate: 5
paginate_path: "/blog/:num/"

defaults:
  -
    scope:
      path: "resources"
      layout: null
    values:
      sitemap: false
      hidden: true
  -
    scope:
      path: "academy"
    values:
      layout: "course"
      hidden: true
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog-post"
    
      
# Site settings
title: DataSF
email: datasf@sfgov.org
description: "Our mission is to empower use of the City and County of San Francisco's data. Our core product is SF OpenData, the official open data portal."
locale: en_US

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 245f7b
  secondary: 6dbce2  
  secondary-dark: 333333
  accent: 7dd191

owner:
  name: DataSF
  email: 
  twitter: datasf
  google:
    ad-client: 
    ad-slot: 
    plus:
  bio: 
  gravatar:  # 160x160 px image for author byline
disqus-shortname:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datasf
  - title: stack-overflow
    url: http://opendata.stackexchange.com/search?q=san+francisco
  - title: github 
    url: http://github.com/datasf

prose:
  siteurl: 'http://datasf.org'
  metadata:
    academy/_posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'course'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
      - name: 'length'
        field:
          element: 'number'
          label: 'Length of course in hours'
      - name: 'prereq'
        field:
          element: 'textarea'
          label: 'Prerequisites'
