# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
version: 3.0.3

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: ['.c9']

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

url: https://datasf.org

paginate: 5
paginate_path: "/blog/:num/"

collections:
  team_members:
    output: true
  resource_topics:
    output: true
    permalink: '/resources/:title/'

defaults:
  -
    scope:
      path: ""
      type: "team_members"
    values:
      layout: "team-member"
  -
    scope:
      path: "resources"
      layout: null
    values:
      sitemap: false
      hidden: true
  -
    scope:
      path: "academy"
    values:
      layout: "course"
      hidden: true
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "blog-post"
  -
    scope:
      path: ""
      type: "resource_topics"
    values:
      layout: "resource-topic"
    
      
# Site settings
title: DataSF
email: datasf@sfgov.org
description: "Our mission is to empower use of the City and County of San Francisco's data. Our core product is SF OpenData, the official open data portal."
locale: en_US

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 245f7b
  secondary: 6dbce2  
  secondary-dark: 333333
  tertiary: 408bae
  accent: 7dd191

owner:
  name: DataSF
  email: 
  twitter: datasf
  google:
    ad-client: 
    ad-slot: 
    plus:
  bio: 
  gravatar:  # 160x160 px image for author byline
disqus-shortname:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datasf
  - title: stack-overflow
    url: http://opendata.stackexchange.com/search?q=san+francisco
  - title: github 
    url: http://github.com/datasf

subjects:
  - Analysis
  - Visualization
  - Mapping
  - Information Design
  - Data Management
  - Excel
  - Tableau
 
series:
  - Excel
  - Tableau
  
resource_types:
  - Document
  - Guide
  - Toolkit
  - Template
  - Video
  - Spreadsheet
  - Research
  - One Pager
  
media_types:
  - Excel
  - Word
  - Google Doc
  - Google Spreadsheet
  - PDF
  - Link
  
audiences:
  - Data Coordinator
  - Data Publisher
  - DataSF Staff

prose:
  siteurl: 'http://datasf.org'
  metadata:
    academy/_posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'course'
      - name: 'title'
        field:
          element: 'text'
          label: 'Title'
      - name: 'summary'
        field:
          element: 'textarea'
          label: 'Summary'
      - name: "prereq"
        field:
          element: "textarea"
          label: "Prerequisites"
      - name: 'length'
        field:
          element: 'number'
          value: 2
          label: 'Length of course in hours'
      - name: "subject"
        field:
          element: "multiselect"
          label: "Topic Area"
          options:
            - name: "Information Design"
              value: "information-design"
            - name: "Analysis"
              value: "analysis"
            - name: "Mapping"
              value: "mapping"
            - name: "Data Management"
              value: "management"
            - name: "Data Visualization"
              value: "visualization"
      - name: 'instructors'
        field:
          element: "multiselect"
          label: "Instructor(s)"
          options: 
            - name: "Sam Dorward"
              value: "sam_dorward"
            - name: "David Weinzimmer"
              value: "david_weinzimmer"
            - name: "Joy Bonaguro"
              value: "joy_bonaguro"
            - name: "Sherman Luk"
              value: "sherman_luk"
            - name: "Marc Hebert"
              value: "marc_hebert"
            - name: "Jason Lally"
              value: "jason_lally"
            - name: "Aaron Low"
              value: "aaron_low"
            - name: "Ashley Groffenberger"
              value: "ashley_groffenberger"
            - name: "Sam Abbot"
              value: "sam_abbot"
            - name: "Celeste Berg"
              value: "celeste_berg"
            - name: "Jessie Rubin"
              value: "jessie_rubin"